export const mockTweets = [
  {
    id: 1,
    author: "Sarah Chen",
    username: "sarahdev",
    time: "2h",
    content:
      "Just shipped a new feature using Next.js 15 and the performance improvements are incredible! 🚀\n\nThe new caching strategies make everything so much faster.",
    avatar: "/avatar.jpg",
    image: "/1.jpg",
    replies: 24,
    retweets: 156,
    likes: 892,
    impressions: 12500,
  },
  {
    id: 2,
    author: "Alex Rivera",
    username: "alexcodes",
    time: "4h",
    content:
      "Hot take: TypeScript has made me a better JavaScript developer.\n\nThe type safety catches so many bugs before they reach production.",
    avatar: "/avatar.jpg",
    replies: 89,
    retweets: 234,
    likes: 1247,
    impressions: 23400,
  },
  {
    id: 3,
    author: "Maya Patel",
    username: "mayabuilds",
    time: "6h",
    content:
      "Working on a new design system with shadcn/ui. The component library is so well thought out!",
    avatar: "/avatar.jpg",
    image: "/2.jpg",
    replies: 45,
    retweets: 178,
    likes: 654,
    impressions: 8900,
  },
  {
    id: 4,
    author: "Jordan Lee",
    username: "jordantech",
    time: "8h",
    content:
      "Finally understanding React Server Components. The mental model shift is real but it's worth it.\n\nThe performance benefits are game-changing for data-heavy apps.",
    avatar: "/avatar.jpg",
    replies: 67,
    retweets: 289,
    likes: 1456,
    impressions: 18700,
  },
  {
    id: 5,
    author: "Emma Wilson",
    username: "emmawrites",
    time: "10h",
    content:
      "Spent the weekend building a side project. There's something magical about coding on a Saturday morning with coffee ☕",
    avatar: "/avatar.jpg",
    image: "/3.jpg",
    replies: 34,
    retweets: 92,
    likes: 567,
    impressions: 6800,
  },
  {
    id: 6,
    author: "Chris Martinez",
    username: "chrismakes",
    time: "12h",
    content:
      "Pro tip: Always write tests for your critical paths. Future you will thank present you.\n\n#webdev #testing",
    avatar: "/avatar.jpg",
    replies: 56,
    retweets: 445,
    likes: 2134,
    impressions: 34200,
  },
];
