export const mockPosts = [
  {
    id: 1,
    author: "Sarah Chen",
    username: "sarahdev",
    createdAt: "2h",
    content:
      "Just shipped a new feature using Next.js 15 and the performance improvements are incredible! 🚀\n\nThe new caching strategies make everything so much faster.",
    avatarUrl: "/avatar.jpg",
    imageUrl: "/1.jpg",
    commentsCount: 24,
    likesCount: 892,
    impressionsCount: 12500,
  },
  {
    id: 2,
    author: "Alex Rivera",
    username: "alexcodes",
    createdAt: "4h",
    content:
      "Hot take: TypeScript has made me a better JavaScript developer.\n\nThe type safety catches so many bugs before they reach production.",
    avatarUrl: "/avatar.jpg",
    commentsCount: 89,
    likesCount: 1247,
    impressionsCount: 23400,
  },
  {
    id: 3,
    author: "Maya Patel",
    username: "mayabuilds",
    createdAt: "6h",
    content:
      "Working on a new design system with shadcn/ui. The component library is so well thought out!",
    avatarUrl: "/avatar.jpg",
    imageUrl: "/2.jpg",
    commentsCount: 45,
    likesCount: 654,
    impressionsCount: 8900,
  },
  {
    id: 4,
    author: "Jordan Lee",
    username: "jordantech",
    createdAt: "8h",
    content:
      "Finally understanding React Server Components. The mental model shift is real but it's worth it.\n\nThe performance benefits are game-changing for data-heavy apps.",
    avatarUrl: "/avatar.jpg",
    commentsCount: 67,
    likesCount: 1456,
    impressionsCount: 18700,
  },
  {
    id: 5,
    author: "Emma Wilson",
    username: "emmawrites",
    createdAt: "10h",
    content:
      "Spent the weekend building a side project. There's something magical about coding on a Saturday morning with coffee ☕",
    avatarUrl: "/avatar.jpg",
    imageUrl: "/3.jpg",
    commentsCount: 34,
    likesCount: 567,
    impressionsCount: 6800,
  },
  {
    id: 6,
    author: "Chris Martinez",
    username: "chrismakes",
    createdAt: "12h",
    content:
      "Pro tip: Always write tests for your critical paths. Future you will thank present you.\n\n#webdev #testing",
    avatarUrl: "/avatar.jpg",
    commentsCount: 56,
    likesCount: 2134,
    impressionsCount: 34200,
  },
];
